# EFFECT OF PROMOTIONS ON SALES 

### Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np

### Importing both Store and Sales CSV Files

In [2]:
df_store = pd.read_csv(r'C:\Users\babat\Documents\Tutorials\Tech1M DA Bootcamp\Python\Data\store.csv')
df_train = pd.read_csv(r'C:\Users\babat\Documents\Tutorials\Tech1M DA Bootcamp\Python\Data\train.csv')

C:\Users\babat\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


### Eyeballing both dataset to see what they are like

In [3]:
df_train.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [4]:
df_store.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

### Merging Both Datasets for Further Analysis

In [5]:
# With Both dataset having "Store" column connecting them
df = df_store.merge(df_train,on=["Store"])
df.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      1         c          a               1270.0                        9.0   
2      1         c          a               1270.0                        9.0   
3      1         c          a               1270.0                        9.0   
4      1         c          a               1270.0                        9.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2008.0       0              NaN              NaN   
2                    2008.0       0              NaN              NaN   
3                    2008.0       0              NaN              NaN   
4                    2008.0       0              NaN              NaN   

  PromoInterval  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0           NaN          5  2015-07-31   5263        555     1      1   
1           NaN          4  2015-07-30   5020        546     1      1   
2           NaN          3  2015-07-29   4782        523     1      1   
3           NaN          2  2015-07-28   5011        560     1      1   
4           NaN          1  2015-07-27   6102        612     1      1   

  StateHoliday  SchoolHoliday  
0            0              1  
1            0              1  
2            0              1  
3            0              1  
4            0              1

In [6]:
df.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'DayOfWeek',
       'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday'],
      dtype='object')

### Eyeballing the Unique Values of Each Categorical Columns (Expressed Numerically) For Proper Mapping 

In [7]:
df['StoreType'].unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [8]:
df['Assortment'].unique()

array(['a', 'c', 'b'], dtype=object)

In [9]:
df['Open'].unique()

array([1, 0], dtype=int64)

In [10]:
df['Promo2'].unique()

array([0, 1], dtype=int64)

In [11]:
df['Open'].unique()

array([1, 0], dtype=int64)

In [12]:
df['Promo'].unique()

array([1, 0], dtype=int64)

In [13]:
df['StateHoliday'].unique()

array(['0', 'a', 'b', 'c', 0], dtype=object)

In [14]:
df['SchoolHoliday'].unique()

array([1, 0], dtype=int64)

In [15]:
# Mapping the Numerically represented categorical Columns
df['Assortment'] = df['Assortment'].replace(['a','b','c'],['Basic','Extra','Extended'])
df['Open'] = df['Open'].replace([1,0],['Yes','No'])
df['Promo2'] = df['Promo2'].replace([1,0],['Participating', 'Not Participating'])
df['Open'] = df['Open'].replace([1,0], ['Yes','No'])
df['Promo']= df['Promo'].replace([1,0],['Yes', 'No'])
df['StateHoliday']=	df['StateHoliday'].replace(['a','b','c','0'], ['Public Holiday','Easter Holiday', 'Christmas', 'None'])
df['SchoolHoliday']= df['SchoolHoliday'].replace([1,0], ['Yes','No'])


In [16]:
df.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c      Basic               1270.0                        9.0   
1      1         c      Basic               1270.0                        9.0   
2      1         c      Basic               1270.0                        9.0   
3      1         c      Basic               1270.0                        9.0   
4      1         c      Basic               1270.0                        9.0   

   CompetitionOpenSinceYear             Promo2  Promo2SinceWeek  \
0                    2008.0  Not Participating              NaN   
1                    2008.0  Not Participating              NaN   
2                    2008.0  Not Participating              NaN   
3                    2008.0  Not Participating              NaN   
4                    2008.0  Not Participating              NaN   

   Promo2SinceYear PromoInterval  DayOfWeek        Date  Sales  Customers  \
0              NaN           NaN          5  2015-07-31   5263        555   
1              NaN           NaN          4  2015-07-30   5020        546   
2              NaN           NaN          3  2015-07-29   4782        523   
3              NaN           NaN          2  2015-07-28   5011        560   
4              NaN           NaN          1  2015-07-27   6102        612   

  Open Promo StateHoliday SchoolHoliday  
0  Yes   Yes         None           Yes  
1  Yes   Yes         None           Yes  
2  Yes   Yes         None           Yes  
3  Yes   Yes         None           Yes  
4  Yes   Yes         None           Yes

### Extraction of various time measures from the date column

In [17]:
df["DateTime"] = pd.to_datetime(df['Date'], utc = True)

In [18]:
df['Date'] = df.DateTime.dt.date
df['Month'] = df['DateTime'].dt.month
df['Mon_Year'] = df['DateTime'].dt.strftime('%Y-%m')
df['Year'] = df.DateTime.dt.year

In [19]:
df['Seasons'] = np.where(df['Month'].isin([6,7,8,9]),'Summer',
                np.where(df['Month'].isin([10,11]),'Fall',
                np.where(df['Month'].isin([12,1,2]),'Winter',
                np.where(df['Month'].isin([3,4,5]),'Spring',
                'nil'))))

In [20]:
df.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c      Basic               1270.0                        9.0   
1      1         c      Basic               1270.0                        9.0   
2      1         c      Basic               1270.0                        9.0   
3      1         c      Basic               1270.0                        9.0   
4      1         c      Basic               1270.0                        9.0   

   CompetitionOpenSinceYear             Promo2  Promo2SinceWeek  \
0                    2008.0  Not Participating              NaN   
1                    2008.0  Not Participating              NaN   
2                    2008.0  Not Participating              NaN   
3                    2008.0  Not Participating              NaN   
4                    2008.0  Not Participating              NaN   

   Promo2SinceYear PromoInterval  ...  Customers Open  Promo  StateHoliday  \
0              NaN           NaN  ...        555  Yes    Yes          None   
1              NaN           NaN  ...        546  Yes    Yes          None   
2              NaN           NaN  ...        523  Yes    Yes          None   
3              NaN           NaN  ...        560  Yes    Yes          None   
4              NaN           NaN  ...        612  Yes    Yes          None   

  SchoolHoliday                  DateTime Month Mon_Year  Year  Seasons  
0           Yes 2015-07-31 00:00:00+00:00     7  2015-07  2015   Summer  
1           Yes 2015-07-30 00:00:00+00:00     7  2015-07  2015   Summer  
2           Yes 2015-07-29 00:00:00+00:00     7  2015-07  2015   Summer  
3           Yes 2015-07-28 00:00:00+00:00     7  2015-07  2015   Summer  
4           Yes 2015-07-27 00:00:00+00:00     7  2015-07  2015   Summer  

[5 rows x 23 columns]

In [21]:
df.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'DayOfWeek',
       'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'DateTime', 'Month', 'Mon_Year', 'Year', 'Seasons'],
      dtype='object')

### Rearrangement of the Columns to accomodate the newly added columns (date measures)

In [22]:
df = df.loc[:,['Store', 'StoreType', 'Assortment', 'DateTime', 'Date', 'Year', 'Month', 'Mon_Year', 'DayOfWeek', 
                'Seasons', 'Open', 'Sales', 'Customers', 'Promo', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 
                'PromoInterval', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 
                'StateHoliday', 'SchoolHoliday']]
df.head()

Store StoreType Assortment                  DateTime        Date  Year  \
0      1         c      Basic 2015-07-31 00:00:00+00:00  2015-07-31  2015   
1      1         c      Basic 2015-07-30 00:00:00+00:00  2015-07-30  2015   
2      1         c      Basic 2015-07-29 00:00:00+00:00  2015-07-29  2015   
3      1         c      Basic 2015-07-28 00:00:00+00:00  2015-07-28  2015   
4      1         c      Basic 2015-07-27 00:00:00+00:00  2015-07-27  2015   

   Month Mon_Year  DayOfWeek Seasons  ... Promo             Promo2  \
0      7  2015-07          5  Summer  ...   Yes  Not Participating   
1      7  2015-07          4  Summer  ...   Yes  Not Participating   
2      7  2015-07          3  Summer  ...   Yes  Not Participating   
3      7  2015-07          2  Summer  ...   Yes  Not Participating   
4      7  2015-07          1  Summer  ...   Yes  Not Participating   

   Promo2SinceWeek Promo2SinceYear PromoInterval  CompetitionDistance  \
0              NaN             NaN           NaN               1270.0   
1              NaN             NaN           NaN               1270.0   
2              NaN             NaN           NaN               1270.0   
3              NaN             NaN           NaN               1270.0   
4              NaN             NaN           NaN               1270.0   

   CompetitionOpenSinceMonth CompetitionOpenSinceYear  StateHoliday  \
0                        9.0                   2008.0          None   
1                        9.0                   2008.0          None   
2                        9.0                   2008.0          None   
3                        9.0                   2008.0          None   
4                        9.0                   2008.0          None   

   SchoolHoliday  
0            Yes  
1            Yes  
2            Yes  
3            Yes  
4            Yes  

[5 rows x 23 columns]

In [23]:
df.describe()

Store          Year         Month     DayOfWeek         Sales  \
count  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06   
mean   5.584297e+02  2.013832e+03  5.846762e+00  3.998341e+00  5.773819e+03   
std    3.219087e+02  7.773960e-01  3.326097e+00  1.997391e+00  3.849926e+03   
min    1.000000e+00  2.013000e+03  1.000000e+00  1.000000e+00  0.000000e+00   
25%    2.800000e+02  2.013000e+03  3.000000e+00  2.000000e+00  3.727000e+03   
50%    5.580000e+02  2.014000e+03  6.000000e+00  4.000000e+00  5.744000e+03   
75%    8.380000e+02  2.014000e+03  8.000000e+00  6.000000e+00  7.856000e+03   
max    1.115000e+03  2.015000e+03  1.200000e+01  7.000000e+00  4.155100e+04   

          Customers  Promo2SinceWeek  Promo2SinceYear  CompetitionDistance  \
count  1.017209e+06    509178.000000    509178.000000         1.014567e+06   
mean   6.331459e+02        23.269093      2011.752774         5.430086e+03   
std    4.644117e+02        14.095973         1.662870         7.715324e+03   
min    0.000000e+00         1.000000      2009.000000         2.000000e+01   
25%    4.050000e+02        13.000000      2011.000000         7.100000e+02   
50%    6.090000e+02        22.000000      2012.000000         2.330000e+03   
75%    8.370000e+02        37.000000      2013.000000         6.890000e+03   
max    7.388000e+03        50.000000      2015.000000         7.586000e+04   

       CompetitionOpenSinceMonth  CompetitionOpenSinceYear  
count              693861.000000             693861.000000  
mean                    7.222866               2008.690228  
std                     3.211832                  5.992644  
min                     1.000000               1900.000000  
25%                     4.000000               2006.000000  
50%                     8.000000               2010.000000  
75%                    10.000000               2013.000000  
max                    12.000000               2015.000000

In [24]:
df = df.fillna(0, inplace = True)

### Dropping Datetime Column to prevent redundancy

In [25]:
df = df.drop(['DateTime'], axis = 1, inplace = True)

AttributeError: 'NoneType' object has no attribute 'drop'

## DATA ANALYSIS AND VISUALIZATION

### Top Ten Store By Sales


In [29]:
df_storesales_top = df.pivot_table(index = 'Store', values= 'Sales', 
                aggfunc=sum).sort_values('Sales', ascending=False).head(10)
df_storesales_top

AttributeError: 'NoneType' object has no attribute 'pivot_table'

In [27]:
df_storesales_top.plot(y= 'Sales', 
                    kind = 'bar',
                    figsize=(12,6), 
                    xlabel = 'Store Number', 
                    ylabel = 'Total Sales', 
                    title= 'TOP TEN STORE BY SALES')

NameError: name 'df_storesales_top' is not defined

### Top Ten Store By Customer Patronage

In [ ]:
(df.groupby(['Store'])["Customers"].sum().reset_index(name = "Total Customers Patronage").sort_values
                        ('Total Customers Patronage', ascending=False).head(10)).plot(
                            y= 'Total Customers Patronage', 
                            kind = 'bar',
                            figsize=(12,6), 
                            xlabel = 'Store Number', 
                            ylabel = 'Total Customer Patronage', 
                            title= 'TOP TEN STORE BY CUSTOMER PATRONAGE')

### Total Monthly Sales Over The Period in Consideration

In [ ]:
df = df.set_index(pd.to_datetime(df['Date']))
df = df.sort_index(ascending=False)

In [ ]:
df_date_sales = df.groupby(["Mon_Year"])["Sales"].sum().reset_index(name = "Total_Sales")
df_date_sales

In [ ]:
df_date_sales.plot("Mon_Year", "Total_Sales", kind='line', linewidth=1.0, figsize=(12, 6), title = "Monthly Sales",
       xlabel = "Month",
       ylabel = "Total Sales (Hundred Million Dollars)")

### Analyzing Total Sales Based on Assortment of Products Sold

In [ ]:
df.pivot_table(index= 'Assortment', values=['Customers', 'Sales'], aggfunc=sum)


In [ ]:
df_assortment = df.groupby(['Assortment'])['Sales'].sum().reset_index(name = "Total Sales")
df_assortment

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8, 8))
labels = df_assortment['Assortment']
sizes = df_assortment['Total Sales']
colors = ['orange', 'blue', 'green']
textprops = {"fontsize":14,'color':'white'}
plt.pie(sizes, labels=labels, colors=colors,
 autopct= '%.2f%%',
 pctdistance =0.8,
 shadow=False,
 textprops =textprops,
 wedgeprops={'linewidth': 3.0},)
 
centre_circle = plt.Circle((0,0),0.65,color= 'grey', fc='white',linewidth=1.00)
fig = plt.gcf()
fig.gca().add_artist(centre_circle)
plt.axis('equal')
plt.show()

### Analyzing Assortment of Product Sales Peculiar to Each Store Type

In [ ]:
df.pivot_table(index= 'StoreType', columns='Assortment', values=['Sales'], aggfunc=sum)

In [ ]:
(df.pivot_table(index= 'StoreType', columns='Assortment', values=['Sales'], aggfunc=sum)).plot(
    kind = 'bar',
    y = 'Sales',
    figsize= (12,6),
    title= 'Store Type Total Sales Based On Assortment of Products',
    ylabel= 'Total Sales (in Billion Dollars'
)

### Analyzing Promotion Effects on Total Sales Over Time 

In [ ]:
df.pivot_table(columns= 'Promo', values=[ 'Sales', 'Customers'], aggfunc=sum)

In [ ]:
(df.pivot_table(columns= 'Promo', values=[ 'Sales', 'Customers'], aggfunc=sum)).plot(kind = 'bar', figsize=(12,6))

In [ ]:
df_promo_sales = df.pivot_table(index= 'Mon_Year', columns= 'Promo', values=[ 'Sales'], aggfunc=sum)
df_promo_sales

In [ ]:
df_promo_sales.plot( 
    kind='line', 
    linewidth=1.0, 
    figsize=(12, 6), 
    title = "Promotion Effect on Monthly Revenue",
    xlabel = "Date",
    ylabel = "Total Sales (Hundred Million Dollars)"   
)

### Analyzing Promotion Effects on Customer Patronage And Sales on Weekdays


In [ ]:
df_Weekday_Trans = df.pivot_table(index= 'DayOfWeek', columns= 'Promo', values=[ 'Sales', 'Customers'], aggfunc=sum)
df_Weekday_Trans

In [ ]:
df_Weekday_Trans.plot(y = 'Customers',
                    kind = 'bar',
                    figsize=(12,6), 
                    xlabel = 'Day Of Week', 
                    ylabel = 'Customer Patronage(Ten Millions)', 
                    title= 'EFFECT OF PROMOTION ON CUSTOMER PATRONAGE')

In [ ]:
df_Weekday_Trans.plot(y = 'Sales',
                    kind = 'bar',
                    figsize=(12,6), 
                    xlabel = 'Day Of Week', 
                    ylabel = 'Total Sales(Ten Millions)', 
                    title= 'EFFECT OF PROMOTION ON DAILY SALES')

# CONCLUSIONS

1. Store 262 and 732 turned in the most revenue and customer patronage respectively of all stores under study,
2. December 2013 realized most revenue for the Month in consideration,
3. Not Suprisingly, "Basic" Assortment Goods Experienced more patronage and inturn contributed more to the revenue of rossman stores in total,
4. StoreType "b" had highest revenue generated of all storetypes also it is the only one that offer "Extra" Assortment Goods Sales to customers of all the five Store types,
5. Even though there seems to be not much difference in the number of patronage where there is promo offer and when there is not, consumers seems to spend more when there is promo than when there is not,
5. With the exception of Saturday and Sunday (With no records of Promo on those days),Total Revenue and Patronage increase for days when promo are made than when they are not.

